### ISSUE TITLE
Dependence on Bioconductor hosted packages

### ISSUE THREAD

**Issue by CGMossa** [petebaker/gnumaker#1]
This package depends on three packages that is in BioConductor and not CRAN. 
```
Skipping 3 packages not available: Rgraphviz, graph, RBGL
```

There must be a way to specify this. For now, I think what needs to be done is
```r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("RBGL")
BiocManager::install("Rgraphviz")
```

I think {graph} is installed automatically via {Rgraphviz}. 

(PS: Lovely package! I'd love to make it a stable in my workflow, so I'll be reporting some more issues and possible PRs, if that's okay!)

**Comment by petebaker** [comment]
Hi CGMossa

Thanks very much for your insights

What you say is very true, installation requires two BioConductor packages and graph automatically as a dependency. Some of this used to be on CRAN but appears to be totally moved to BioConductor these days.

You seem to have a nice solution so I will include that in the documenttation. I would love to make it automatic but not sure how just yet. My guess is that an alternative may also be to use something like

```r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
devtools::install_github("petebaker/gnumaker", repos = BiocManager::repositories())

```
which will then use the Bioconductor repos as well as rstudio CRAN ones to install the latest versions of any CRAN or BioConductor packages not already installed. It may not work if a user has an oldish version of BioConductor installed so I will investigate.

Unfortunately, I've been snowed under with course redevelopment and other teaching stuff for the last 6 months or so haven't looked at gnumaker at all until today. However, this week I'm making a concerted effort to get back to research and coding so I welcome any other thoughts or fixes that you have!

Regards
Peter

**Comment by petebaker** [comment]
Also, there is apparently a trick that can be used with DESCRIPTION file to add the line

```r
biocViews:
```

and then it looks for BioConductor packages but this is not documented
[https://github.com/r-lib/devtools/issues/700](https://github.com/r-lib/devtools/issues/700)
[https://bioinformatics.stackexchange.com/questions/3365/r-package-development-how-does-one-automatically-install-bioconductor-packages](https://bioinformatics.stackexchange.com/questions/3365/r-package-development-how-does-one-automatically-install-bioconductor-packages) 
but I really don't know about this

Regards
Peter

**Comment by CGMossa** [comment]
Hmm yeah that looks like the way to do it.

It is nice when there is a tracking issue on these things, but it is not
really urgent..

**Comment by petebaker** [comment]
Thanks Mossa!

I've included biocViews: line in DESCRIPTION and that seems to work well including updating BioConductor packages.

Please re-open issue if this tuns out not to work so well

Regards
Peter
